### ISSUE TITLE
Consider renaming to `swc-ephys`

### ISSUE THREAD

**Issue by adamltyson** [neuroinformatics-unit/spikewrap#42]
The smallest of small suggestions, but every other repo we have uses hyphens, and it would be great if these were consistent.

**Comment by JoeZiminski** [comment]
That's a good idea, maybe now is a good time to think of a better name, I was thinking of adding to PyPI soon for easy installation. I am terrible at names though :'D, some ideas:

- SpikeRunner
- eceFlow
- SpikeFlow
- SpikeShepard

🤷

**Comment by adamltyson** [comment]
I like both `spikeflow` and `spikerunner`. I also like not having `swc` in the name, so that its clear that others can use it.
